### ISSUE TITLE
Update dcc-repository, AWS to use SONG importer

### ISSUE THREAD

**Issue by rtisma** [icgc-dcc/dcc-repository#16]

**Comment by Fgerthoffert** [comment]
Get into the POM file an increment version of the AWS sdk

**Comment by andricDu** [comment]
Changing scope of ticket.

Even though the S3 Errors that are being reported are correct, the importer should no longer be relying on the listing of the S3 Bucket directly. Instead this entire importer should be using the SONG implementation, rather the cloud/S3 based implementation. 

This is a dependency for merge: https://github.com/icgc-dcc/dcc-repository/pull/13 before direct work can begin.

I've updated the story points 1->5 to reflect the increased complexity and difficulty.

**Comment by andricDu** [comment]
https://github.com/icgc-dcc/dcc-repository/pull/18
