### ISSUE TITLE
Update Download Files box to generate manifest ID using score-client instead of icgc-storage-client

### ISSUE THREAD

**Issue by hknahal** [icgc-dcc/dcc-repository#25]
The command generated after clicking on "Download Files" -> "Manifest ID" should be updated to use `score-client`. Currently, it prints the command using `icgc-storage-client` (see screenshot below):

![update_to_score_client](https://user-images.githubusercontent.com/4992044/43980901-d43072da-9cbd-11e8-9e81-72b7a274db2f.png)

**Comment by alekspejovic** [comment]
This was fixed, and is in prod.
![Screen Shot 2019-01-16 at 2.55.48 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5beaeda44f12fd00123cac0e/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77226455f56b7191a37af1172e4f5b575ecc3c4a4356bcbbd671f3e57862804e0ebcd0390c77ce6e43a5e9871fb701bb288e468ce4e9df49d2f42f67b6d5db1063474f4dcbed5727a19041c95df24ce74b5da11b3464e3742431.png)
