### ISSUE TITLE
Don't index PCAWG2 SONG entries

### ISSUE THREAD

**Issue by alekspejovic** [icgc-dcc/dcc-repository#37]
Skip indexing SONG entries produced by the PCAWG2 alignment workflow. 

Condition : Do not index entries where :

"info": {
    "dataset": [
      "PCAWG2"
    ]

**Comment by alekspejovic** [comment]
@junjun-zhang Can you confirm this is the exact requirement?

**Comment by junjun-zhang** [comment]
@alekspejovic yes, the requirement is accurate.

**Comment by KevinFHartmann** [comment]
We have multiple fields labeled "info" in a SONG analysis.

@junjun-zhang / @alekspejovic 
To be specific, we're talking about the "info" field for the top level analysis, correct? That is, we do not index an analysis with the SONG indexer component IF all the following conditions are all true: 
1) there is an info field at the top level of the analysis,
 2) inside the info field there is an array field called "dataset",
 and 
3) there exists a string anywhere in the "dataset" array labeled "PCAWG2".

Is that correct?

**Comment by alekspejovic** [comment]
@KevinFHartmann That is correct.

Here is an example of a full SONG analysis payload which should NOT be indexed. 


[examplepayload.txt](https://github.com/icgc-dcc/dcc-repository/files/2989856/examplepayload.txt)
