### ISSUE TITLE
Issue with generating manifests for PDC file entries

### ISSUE THREAD

**Issue by alekspejovic** [icgc-dcc/dcc-repository#39]
- The half-song PDC files are now showing up on production
- The repository field is showing up as empty for PDC fields when ExperimentalStrategy = 'Validation' or when Software = 'Pilot50'.

As a result, the downloaded manifest is also empty.

https://dcc.icgc.org/repositories?filters=%7B%22file%22:%7B%22repoName%22:%7B%22is%22:%5B%22PDC%20-%20Chicago%22%5D%7D,%22experimentalStrategy%22:%7B%22is%22:%5B%22Validation%22%5D%7D%7D%7D&files=%7B%22from%22:51,%22size%22:50%7D
![image.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5beaeda44f12fd00123cac0e/125516c66e82c728ace21e0d46e1999b2487c1e5cdf9ad4cae58f3806b1c65262855a72823dde02ae6432e51575f4fa444515616a9ac8c39baa47e21d40854b088270a36d43703adbf881eba04b82389478cb1b5894bc1fa70.png)

https://dcc.icgc.org/repositories?filters=%7B%22file%22:%7B%22repoName%22:%7B%22is%22:%5B%22PDC%20-%20Chicago%22%5D%7D,%22experimentalStrategy%22:%7B%22is%22:%5B%22Validation%22%5D%7D%7D%7D&files=%7B%22from%22:51,%22size%22:50%7D
![image (1)](https://user-images.githubusercontent.com/12387683/54149335-3fab5480-440c-11e9-9a8a-5a08d01acddb.png)

*Expected Behaviour*
The Repository field should be set as PDC so that the manifest will download the set of files ids.

**Comment by alekspejovic** [comment]
Scenario 1:
Filtering on PCAWG pilot50 variant call VF files, when you try and generate a manifest for the entire filter section, the manifest is empty. However, when you checkmark a subset of files, the manifest produces succesfully. 

https://icgc.org/ZCi

Same for, https://icgc.org/ZC5 & https://icgc.org/ZCS. 

See ticket https://github.com/icgc-dcc/dcc-portal/issues/606 for other scenarios of failed manifest generation.

**Comment by andricDu** [comment]
I've marked this as closed due to the original scope of the ticket being completed.
